services:
  # frontend:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      /env/postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    env_file:
      /env/redis.env
    volumes:
      - redis-data:/data

networks:
  internal:
    driver: bridge

volumes:
  postgres-data:
  redis-data: