services:
  # frontend:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    env_file:
      /env/postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:8.0.2-alpine
    container_name: redis
    restart: always
    env_file:
      /env/redis.env
    volumes:
      - redis-data:/data
      - ./backend/data_model.sql:/docker-entrypoint-initdb.d/data_model.sql
    shm_size: 128mb

networks:
  internal:
    driver: bridge

volumes:
  postgres-data:
  redis-data: