# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import balance_pb2 as balance__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in balance_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BalanceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddBalance = channel.unary_unary(
                '/balance.BalanceService/AddBalance',
                request_serializer=balance__pb2.AddBalanceRequest.SerializeToString,
                response_deserializer=balance__pb2.AddBalanceResponse.FromString,
                _registered_method=True)
        self.GetBalanceByUser = channel.unary_unary(
                '/balance.BalanceService/GetBalanceByUser',
                request_serializer=balance__pb2.GetBalanceByUserRequest.SerializeToString,
                response_deserializer=balance__pb2.GetBalanceByUserResponse.FromString,
                _registered_method=True)
        self.UpdateBalance = channel.unary_unary(
                '/balance.BalanceService/UpdateBalance',
                request_serializer=balance__pb2.UpdateBalanceRequest.SerializeToString,
                response_deserializer=balance__pb2.UpdateBalanceResponse.FromString,
                _registered_method=True)


class BalanceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalanceByUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BalanceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBalance,
                    request_deserializer=balance__pb2.AddBalanceRequest.FromString,
                    response_serializer=balance__pb2.AddBalanceResponse.SerializeToString,
            ),
            'GetBalanceByUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalanceByUser,
                    request_deserializer=balance__pb2.GetBalanceByUserRequest.FromString,
                    response_serializer=balance__pb2.GetBalanceByUserResponse.SerializeToString,
            ),
            'UpdateBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBalance,
                    request_deserializer=balance__pb2.UpdateBalanceRequest.FromString,
                    response_serializer=balance__pb2.UpdateBalanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'balance.BalanceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('balance.BalanceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BalanceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/balance.BalanceService/AddBalance',
            balance__pb2.AddBalanceRequest.SerializeToString,
            balance__pb2.AddBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalanceByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/balance.BalanceService/GetBalanceByUser',
            balance__pb2.GetBalanceByUserRequest.SerializeToString,
            balance__pb2.GetBalanceByUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/balance.BalanceService/UpdateBalance',
            balance__pb2.UpdateBalanceRequest.SerializeToString,
            balance__pb2.UpdateBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
