# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: balance.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'balance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbalance.proto\x12\x07\x62\x61lance\"4\n\x11\x41\x64\x64\x42\x61lanceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\"G\n\x12\x41\x64\x64\x42\x61lanceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x02\"*\n\x17GetBalanceByUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"M\n\x18GetBalanceByUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x02\"7\n\x14UpdateBalanceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\"J\n\x15UpdateBalanceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x02\x32\x80\x02\n\x0e\x42\x61lanceService\x12\x45\n\nAddBalance\x12\x1a.balance.AddBalanceRequest\x1a\x1b.balance.AddBalanceResponse\x12W\n\x10GetBalanceByUser\x12 .balance.GetBalanceByUserRequest\x1a!.balance.GetBalanceByUserResponse\x12N\n\rUpdateBalance\x12\x1d.balance.UpdateBalanceRequest\x1a\x1e.balance.UpdateBalanceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'balance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDBALANCEREQUEST']._serialized_start=26
  _globals['_ADDBALANCEREQUEST']._serialized_end=78
  _globals['_ADDBALANCERESPONSE']._serialized_start=80
  _globals['_ADDBALANCERESPONSE']._serialized_end=151
  _globals['_GETBALANCEBYUSERREQUEST']._serialized_start=153
  _globals['_GETBALANCEBYUSERREQUEST']._serialized_end=195
  _globals['_GETBALANCEBYUSERRESPONSE']._serialized_start=197
  _globals['_GETBALANCEBYUSERRESPONSE']._serialized_end=274
  _globals['_UPDATEBALANCEREQUEST']._serialized_start=276
  _globals['_UPDATEBALANCEREQUEST']._serialized_end=331
  _globals['_UPDATEBALANCERESPONSE']._serialized_start=333
  _globals['_UPDATEBALANCERESPONSE']._serialized_end=407
  _globals['_BALANCESERVICE']._serialized_start=410
  _globals['_BALANCESERVICE']._serialized_end=666
# @@protoc_insertion_point(module_scope)
